# Generated by Django 3.2 on 2021-05-04 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_auto_20210425_0954'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthSecret',
        ),
    ]
