# Generated by Django 3.2 on 2021-05-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_delete_authsecret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret2',
            field=models.TextField(default=''),
        ),
    ]
